name: Pack Contoso_University_Core

on:

 push:
<<<<<<< HEAD
  paths:
   - contents/**
=======

 paths:

 - contents/**

>>>>>>> af0fa5c0815cf69bc36d93f7be9113f47720a39a
 workflow_dispatch:

jobs:

 build:
<<<<<<< HEAD
  runs-on: windows-latest
  steps:
  - uses: actions/checkout@v2
  - uses: microsoft/powerplatform-actions/pack-solution@v0
    with:
      solution-file: out/contoso_university_core.zip
      solution-folder: contents
      solution-type: Both
  - uses: actions/upload-artifact@v2
    with:
      name: packed-solution
      path: out/
=======

 runs-on: windows-latest

 steps:

 - uses: actions/checkout@v2

 - uses: microsoft/powerplatform-actions/pack-solution@v0

 with:

 solution-file: out/contoso_university_core.zip

 solution-folder: contents

 solution-type: Both

  - uses: actions/upload-artifact@v2

 with:

 name: packed-solution

 path: out/
>>>>>>> af0fa5c0815cf69bc36d93f7be9113f47720a39a
